export const CONCEPT_ALIASES: Record<string, string[]> = {
  "general-ledger": ["GL", "general ledger", "the books", "ledger"],
  "chart-of-accounts": ["COA", "chart of accounts", "GL accounts"],
  "journal-entries": ["JE", "journals", "journal entry", "manual journal"],
  dimensions: ["dims", "dimension", "UDD", "user-defined dimension"],
  "accounts-payable": ["AP", "payables", "bills"],
  "accounts-receivable": ["AR", "receivables", "invoices", "customers"],
  "cash-management": ["cash", "treasury", "bank accounts"],
  "bank-reconciliation": ["bank rec", "reconciliation", "reconcile bank"],
  budgets: ["budget", "forecast", "budget vs actual"],
  "financial-reporting": [
    "reports",
    "financial statements",
    "P&L",
    "income statement",
    "balance sheet",
  ],
  "multi-entity": ["multi entity", "entities", "subsidiaries"],
  "multi-currency": ["currency", "FX", "exchange rates"],
  consolidation: ["consolidations", "eliminations"],
  vendors: ["vendor", "supplier"],
  purchasing: ["PO", "purchase orders", "procure"],
  "revenue-recognition": ["rev rec", "ASC 606"],
  contracts: ["contract", "subscription billing"],
  "inventory-control": ["inventory", "stock"],
  projects: ["project accounting", "PSA"],
  "user-roles": ["permissions", "roles", "users"],
  "sage-ai": ["intelligent GL", "AI GL"],
  "platform-services": ["platform", "customization"],
  "order-entry": ["OE", "sales orders", "orders"],
  "fixed-assets": ["FA", "assets", "depreciation"],
  "time-expenses": ["T&E", "timesheets"],
  "employee-expenses": ["expense reports", "expenses"],
  "tax-management": ["tax", "VAT", "GST"],
  allocations: ["account allocations", "allocations"],
  "landed-costs": ["landed cost"],
  "smart-events": ["smart event", "triggers"],
  "ap-automation": ["bill capture", "OCR bills"],
  dashboards: ["dashboard", "KPI"],
  "vendor-payments": ["payments", "ACH", "pay bills"],
  construction: ["WIP", "construction"],
  "sage-copilot": ["copilot", "sage copilots"],
  "close-books": ["close the books", "closing books", "lock books", "book close"],
  "reporting-periods": ["reporting period", "fiscal period", "accounting period"],
  "close-workspace": ["close workspace", "close automation", "period close checklist"],
};
